# Configuration for es-node3
cluster.name: es
node.name: es-node3
node.roles: [master, data, ingest]

# Network settings
http.port: 31922
transport.port: 9302

# Path settings
path.data: /data1/elk/elasticsearch/dev-utils/data/es/es-node3
path.logs: /data1/elk/elasticsearch/dev-utils/logs/es/es-node3
